// ---------------------------------------------------------------------------
// FHIR R4 substrate — serves the resources generated by
// scripts/synthea-to-fhir.mjs (data/fhir/<ResourceType>/<id>.json) and the
// PAS-shaped prior-auth submission endpoint the v1 decision workflow consumes.
//
// Regen the resource store with `make fhir-regen`. See docs/FHIR_SUBSTRATE.md.
// ---------------------------------------------------------------------------
import { Router } from "express"
import { logger, emitEvent } from "@proofpa/observability"
import { randomUUID } from "node:crypto"
import { existsSync, readdirSync, readFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

// services/provider-adapter-api/src -> repo root
const REPO_ROOT = join(dirname(fileURLToPath(import.meta.url)), "..", "..", "..")
const FHIR_DIR = join(REPO_ROOT, "data", "fhir")
const LETTERS_DIR = join(REPO_ROOT, "data", "necessity-letters")

const NECESSITY_LETTER_SYSTEM = "https://ease-ehealth.example/necessity-letter"
const EXT_REQUESTED_AMOUNT = "https://ease-ehealth.example/fhir/StructureDefinition/requested-amount"

// Minimal structural type for the generated resources — we only reach into
// the fields the substrate actually serves/resolves.
type FhirResource = {
  resourceType: string
  id: string
  [key: string]: unknown
}

const RESOURCE_TYPES = [
  "Patient",
  "Coverage",
  "Condition",
  "Procedure",
  "ServiceRequest",
  "DocumentReference",
] as const

// ─── Store ───────────────────────────────────────────────────────────
// Loaded once at startup; the store is regenerated offline via fhir-regen.
function loadFhirStore(): Map<string, Map<string, FhirResource>> {
  const store = new Map<string, Map<string, FhirResource>>()
  for (const type of RESOURCE_TYPES) {
    const byId = new Map<string, FhirResource>()
    const dir = join(FHIR_DIR, type)
    if (existsSync(dir)) {
      for (const file of readdirSync(dir)) {
        if (!file.endsWith(".json")) continue
        const resource = JSON.parse(readFileSync(join(dir, file), "utf8")) as FhirResource
        byId.set(resource.id, resource)
      }
    }
    store.set(type, byId)
  }
  return store
}

const fhirStore = loadFhirStore()
const storeCount = [...fhirStore.values()].reduce((n, m) => n + m.size, 0)
if (storeCount === 0) {
  logger.warn({ fhir_dir: FHIR_DIR }, "FHIR store is empty — run `make fhir-regen` to populate data/fhir/")
} else {
  logger.info({ fhir_dir: FHIR_DIR, resources: storeCount }, "FHIR store loaded")
}

function operationOutcome(diagnostics: string) {
  return {
    resourceType: "OperationOutcome",
    issue: [{ severity: "error", code: "not-found", diagnostics }],
  }
}

// "Patient/abc" | "abc" -> "abc"
const refId = (reference: string | undefined): string | undefined =>
  reference?.split("/").pop()

function referencesPatient(resource: FhirResource, patientId: string): boolean {
  const refs = [
    (resource.subject as { reference?: string } | undefined)?.reference,
    (resource.beneficiary as { reference?: string } | undefined)?.reference,
    (resource.patient as { reference?: string } | undefined)?.reference,
  ]
  return resource.id === patientId || refs.some((r) => r === `Patient/${patientId}`)
}

export const fhirRouter = Router()

// ─── Read: GET /fhir/r4/{ResourceType}/{id} ──────────────────────────
// (Registered after the $content route so the literal segment wins.)

// ─── Letter content: the DocumentReference attachment payload ────────
// content.attachment.url on dr-* resources points here; the identifier in
// system https://ease-ehealth.example/necessity-letter names the letter file
// (data/necessity-letters/<value>.md) — same convention the attester adapter
// uses (letters keyed by procedure code).
fhirRouter.get("/fhir/r4/DocumentReference/:id/\\$content", (req, res) => {
  const doc = fhirStore.get("DocumentReference")?.get(req.params.id)
  if (!doc) {
    res.status(404).json(operationOutcome(`DocumentReference/${req.params.id} not found`))
    return
  }
  const identifiers = (doc.identifier ?? []) as Array<{ system?: string; value?: string }>
  const letterKey = identifiers.find((i) => i.system === NECESSITY_LETTER_SYSTEM)?.value
  const letterPath = letterKey ? join(LETTERS_DIR, `${letterKey}.md`) : undefined
  if (!letterPath || !existsSync(letterPath)) {
    res.status(404).json(operationOutcome(`No letter content on file for DocumentReference/${req.params.id}`))
    return
  }
  logger.info(
    { correlation_id: req.correlationId, document_reference_id: req.params.id, letter: letterKey },
    "FHIR: serving necessity-letter content",
  )
  res.type("text/markdown").send(readFileSync(letterPath, "utf8"))
})

fhirRouter.get("/fhir/r4/:resourceType/:id", (req, res) => {
  const byId = fhirStore.get(req.params.resourceType)
  if (!byId) {
    res.status(404).json(operationOutcome(`Unsupported resource type: ${req.params.resourceType}`))
    return
  }
  const resource = byId.get(req.params.id)
  if (!resource) {
    res.status(404).json(operationOutcome(`${req.params.resourceType}/${req.params.id} not found`))
    return
  }
  res.json(resource)
})

// ─── Search: GET /fhir/r4/{ResourceType}?patient=<id> ────────────────
fhirRouter.get("/fhir/r4/:resourceType", (req, res) => {
  const byId = fhirStore.get(req.params.resourceType)
  if (!byId) {
    res.status(404).json(operationOutcome(`Unsupported resource type: ${req.params.resourceType}`))
    return
  }
  const patientId = req.query.patient as string | undefined
  const matches = [...byId.values()].filter(
    (r) => !patientId || referencesPatient(r, patientId),
  )
  logger.info(
    { correlation_id: req.correlationId, resource_type: req.params.resourceType, patient: patientId },
    `FHIR search: ${matches.length} ${req.params.resourceType} resources`,
  )
  res.json({
    resourceType: "Bundle",
    type: "searchset",
    total: matches.length,
    entry: matches.map((resource) => ({
      fullUrl: `/fhir/r4/${resource.resourceType}/${resource.id}`,
      resource,
    })),
  })
})

// ─── PAS-shaped submission: POST /v1/prior-auth/fhir-submit ──────────
// Accepts {"serviceRequestId": "...", "correlation_id"?} or a full FHIR
// Bundle containing a ServiceRequest. Resolves the referenced Patient /
// Coverage / provider org and returns the flat "decision request" payload
// consumed by the CRE prior-auth workflow.

interface DecisionRequest {
  correlation_id: string
  service_request_id: string
  patient_id: string
  member_id: string | null
  plan_hash: string | null
  payer_org_id: string | null
  provider_org_id: string | null
  procedure_code: string | null
  amount_usdc: number | null
  service_date: string | null
  document_reference_id: string | null
  letter_url: string | null
}

// In-memory submission log, keyed by correlation_id (demo-scale by design).
const submissions = new Map<string, DecisionRequest>()

function findInBundle(body: FhirResource, type: string, id?: string): FhirResource | undefined {
  const entries = (body.entry ?? []) as Array<{ resource?: FhirResource }>
  return entries
    .map((e) => e.resource)
    .find((r): r is FhirResource => !!r && r.resourceType === type && (!id || r.id === id))
}

function buildDecisionRequest(
  sr: FhirResource,
  bundle: FhirResource | undefined,
  correlationId: string,
): { payload?: DecisionRequest; error?: string } {
  // Bundle entries win over the store so a PAS-style submission is self-contained.
  const resolve = (type: string, reference: string | undefined): FhirResource | undefined => {
    const id = refId(reference)
    if (!id) return undefined
    return (bundle && findInBundle(bundle, type, id)) ?? fhirStore.get(type)?.get(id)
  }

  const patientId = refId((sr.subject as { reference?: string } | undefined)?.reference)
  if (!patientId) return { error: "ServiceRequest.subject must reference a Patient" }

  const insurance = (sr.insurance ?? []) as Array<{ reference?: string }>
  const coverage = resolve("Coverage", insurance[0]?.reference)
  if (!coverage) return { error: "ServiceRequest.insurance must reference a resolvable Coverage" }

  const coverageClass = (coverage.class ?? []) as Array<{
    type?: { coding?: Array<{ code?: string }> }
    value?: string
  }>
  const planHash =
    coverageClass.find((c) => c.type?.coding?.some((coding) => coding.code === "plan"))?.value ?? null

  const payerOrgId =
    refId(((coverage.payor ?? []) as Array<{ reference?: string }>)[0]?.reference) ?? null
  const providerOrgId = refId((sr.requester as { reference?: string } | undefined)?.reference) ?? null

  const codings = ((sr.code as { coding?: Array<{ system?: string; code?: string }> } | undefined)?.coding ?? [])
  const procedureCode =
    codings.find((c) => c.system === "http://www.ama-assn.org/go/cpt")?.code ?? codings[0]?.code ?? null

  const amountExt = ((sr.extension ?? []) as Array<{ url?: string; valueMoney?: { value?: number } }>).find(
    (e) => e.url === EXT_REQUESTED_AMOUNT,
  )
  const amountUsd = amountExt?.valueMoney?.value
  const amountUsdc = typeof amountUsd === "number" ? Math.round(amountUsd * 1_000_000) : null

  const documentReferenceId =
    refId(((sr.supportingInfo ?? []) as Array<{ reference?: string }>)[0]?.reference) ?? null

  return {
    payload: {
      correlation_id: correlationId,
      service_request_id: sr.id,
      patient_id: patientId,
      member_id: (coverage.subscriberId as string | undefined) ?? null,
      plan_hash: planHash,
      payer_org_id: payerOrgId,
      provider_org_id: providerOrgId,
      procedure_code: procedureCode,
      amount_usdc: amountUsdc,
      service_date: (sr.occurrenceDateTime as string | undefined) ?? null,
      document_reference_id: documentReferenceId,
      letter_url: documentReferenceId
        ? `/fhir/r4/DocumentReference/${documentReferenceId}/$content`
        : null,
    },
  }
}

fhirRouter.post("/v1/prior-auth/fhir-submit", (req, res) => {
  const body = req.body as FhirResource & { serviceRequestId?: string; correlation_id?: string }

  let sr: FhirResource | undefined
  let bundle: FhirResource | undefined
  if (body?.resourceType === "Bundle") {
    bundle = body
    sr = findInBundle(body, "ServiceRequest")
    if (!sr) {
      res.status(400).json({ error: "Bundle contains no ServiceRequest" })
      return
    }
  } else if (typeof body?.serviceRequestId === "string" && body.serviceRequestId.length > 0) {
    sr = fhirStore.get("ServiceRequest")?.get(body.serviceRequestId)
    if (!sr) {
      res.status(404).json(operationOutcome(`ServiceRequest/${body.serviceRequestId} not found`))
      return
    }
  } else {
    res.status(400).json({ error: "Body must be {serviceRequestId} or a FHIR Bundle with a ServiceRequest" })
    return
  }

  const correlationId = body.correlation_id ?? req.correlationId ?? randomUUID()
  const { payload, error } = buildDecisionRequest(sr, bundle, correlationId)
  if (!payload) {
    res.status(422).json({ error })
    return
  }

  submissions.set(correlationId, payload)
  emitEvent({
    correlation_id: correlationId,
    stage: "fhir_prior_auth_submitted",
    status: "success",
    metadata: {
      service_request_id: payload.service_request_id,
      procedure_code: payload.procedure_code,
      amount_usdc: payload.amount_usdc,
      plan_hash: payload.plan_hash,
    },
  })
  logger.info(
    { correlation_id: correlationId, service_request_id: payload.service_request_id },
    `FHIR prior auth submitted: ${payload.procedure_code} for Patient/${payload.patient_id} — ${payload.amount_usdc} USDC(6)`,
  )
  res.status(202).json(payload)
})

fhirRouter.get("/v1/prior-auth/submissions/:correlationId", (req, res) => {
  const submission = submissions.get(req.params.correlationId)
  if (!submission) {
    res.status(404).json({ error: "Submission not found", correlation_id: req.params.correlationId })
    return
  }
  res.json(submission)
})
